typography_spectrum: 0.893285610480234
color:
  brandColors:
    - '#ffffff'
    - '#a3bf37'
    - '#6aa143'
    - '#cedcbe'
    - '#aece99'
  brandStrength: 0.11029999353922904
  lightness: 0.7839799250941724
  saturation: 0.9384905456099659
  rhythmicContrast: 0.9481017547659576
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.986418679356575
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Gabriela Lerner
  email: gabriela@radiantonraw.co.uk
  url: radiantonraw.co.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/861a41c1-d9ee-4e50-99ea-57b71ebd150e.jpg
name: radiantonraw
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Gabriela
    url: 'http://www.radiantonraw.co.uk'
    type: external
favicon: null
title: Healthy Living Tips with Gabriela Lerner
purpose: []
